"""Definitions 7, 8, 13, 14 and 15: content entailment, the canonical frame,
the base a regime specifies, the frame it induces, and membership in that
frame under the Herbrand interpretation.

Also the range of subjunctive robustness (Definition 6), used by
check_recovery.py to check Lemma 2 numerically on small frames.
"""
from .regime import BOT
from .roles import UNIT, adj_iter
from .content import content_pos, content_neg


def make_good(closure):
    """Membership of a pair ⟨Γ, Δ⟩ of ground triples in I_R (Definition 14,
    "I_B = I_C ∪ {⟨𝔅(Γ), 𝔅(Δ)⟩ | Γ |~_B Δ}") in the Herbrand model
    (Definition 15, 𝔅 the identity on ground triples over N), with

      I_C  Definition 8 (Canonical frame): "I_C = {⟨Γ, Δ⟩ ∈ S | Γ ∩ Δ ≠ ∅}";
      |~_B Definition 13 (Base specified by R): "Γ |~_{B_R} Δ iff Γ is
           R-inconsistent or Δ ∩ cl_R(Γ) ≠ ∅".

    `closure` is cl_R from make_closure. Note that membership is monotone in
    Γ and in Δ, since cl_R and overlap are; the pruned checks rely on that
    one fact and nothing else (CLAUDE.md, "Pruning")."""
    def good(pair):
        Gam, Del = pair
        if Gam & Del:
            return True                   # I_C
        cl = closure(Gam)
        return BOT in cl or bool(Del & cl)
    return good


def iss_entails(good, G, H, U):
    """Definition 7 (Content entailment): "𝔊 |~ 𝔇 iff ⋃(⊔g⁺_i ⊔ ⊔d⁻_j) ⊆ I".
    For 𝔊 = {⟦G⟧}, 𝔇 = {⟦H⟧} this is, by Lemma 2, "every pair of a set
    generating ⟦G⟧⁺ ⊔ ⟦H⟧⁻ lies in I". Lemma 2 is the one lemma used, and
    it is itself checked numerically (check_recovery.py, check_lemma2)."""
    return all(good(pr) for pr in adj_iter(content_pos(G, U), content_neg(H, U)))


def iss_incoherent(good, G, U):
    """Proposition 2's left-hand side, ⟦G⟧ |~ ∅: "content entailment with the
    empty set of succedent contents (Definition 7), the adjunction over the
    empty family being the role generated by ⟨∅, ∅⟩"."""
    return all(good(pr) for pr in adj_iter(content_pos(G, U), UNIT))


def rsr(S, I, F):
    """Definition 6: the range of subjunctive robustness of F ⊆ S,
    "RSR(H) = {⟨x, y⟩ | ∀⟨𝔊, 𝔇⟩ ∈ H (⟨𝔊 ∪ x, 𝔇 ∪ y⟩ ∈ I)}", computed
    over an explicit finite S (all candidate implications of a tiny frame)."""
    return frozenset(p for p in S if all(((p[0] | x, p[1] | y) in I) for (x, y) in F))
